version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-script.sql:/docker-entrypoint-initdb.d/10-init-script.sql
      - ./postgres/admin-tasks.sql:/docker-entrypoint-initdb.d/20-admin-tasks.sql
    ports:
      - '${BACKEND_PUBLIC_DB_PORT:-5432}:${POSTGRES_PORT:-5432}' # Default to 5432 if BACKEND_PUBLIC_DB_PORT is not set. Needed this to avoid potential conflict with other Postgres instances running on the same host.
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      POSTGRES_INTERNAL_DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/postgres
      BACKEND_PUBLIC_DB_HOST: ${BACKEND_PUBLIC_DB_HOST:-localhost}
      BACKEND_PUBLIC_DB_PORT: ${BACKEND_PUBLIC_DB_PORT:-5432}
      BACKEND_RECAPTCHA_SECRET_KEY: ${BACKEND_RECAPTCHA_SECRET_KEY}

    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    environment:
      FRONTEND_RECAPTCHA_SITE_KEY: ${FRONTEND_RECAPTCHA_SITE_KEY}
      CLI_API_URL: ${CLI_API_URL}
    depends_on:
      - backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3

  cron:
    build: ./cron
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./cron/logs:/var/log
    healthcheck:
      test: ['CMD-SHELL', "pgrep cron || (echo 'Cron not running' && exit 1)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
